### ISSUE TITLE
`npm start` throws (invalid ELF header?)

### ISSUE THREAD

**Issue by serapath** [OpenWebCAD/node-occ-sample#1]
```bash
npm start

> node-occ-sample@0.1.2 start /home/serapath/Desktop/dev/labs/PLAYGROUND/node-occ-sample
> node app

module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/serapath/Desktop/dev/labs/PLAYGROUND/node-occ-sample/node_modules/node-occ/lib/binding/occ.node: invalid ELF header
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/serapath/Desktop/dev/labs/PLAYGROUND/node-occ-sample/node_modules/node-occ/lib/bindings.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-occ-sample@0.1.2 start: `node app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-occ-sample@0.1.2 start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-occ-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-occ-sample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-occ-sample
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serapath/.npm/_logs/2017-04-16T18_04_34_958Z-debug.log
```

**Comment by Johnly1986** [comment]
I also encountered the same problem, how to solve it?
