### ISSUE TITLE
npm start fails in windows PC

### ISSUE THREAD

**Issue by Vishnu-C** [OpenWebCAD/node-occ-sample#7]
OS : Windows 10 64 bit

```
D:\projects\current\Struct\node-occ-sample>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 761 packages in 12.437s

1 package is looking for funding
  run `npm fund` for details

found 1030 vulnerabilities (524 low, 42 moderate, 464 high)
  run `npm audit fix` to fix them, or `npm audit` for details

D:\projects\current\Struct\node-occ-sample>npm start

> node-occ-sample@0.1.2 start D:\projects\current\Struct\node-occ-sample
> node ./node_modules/webpack/bin/webpack.js; node dist/app.js

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'D:\projects\current\Struct\node-occ-sample\node_modules\webpack\bin\webpack.js;'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-occ-sample@0.1.2 start: `node ./node_modules/webpack/bin/webpack.js; node dist/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-occ-sample@0.1.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vishnu\AppData\Roaming\npm-cache\_logs\2020-09-06T14_46_08_580Z-debug.log
```

**Comment by jotarochen** [comment]
+1,应该是作者不再维护node-occ这个依赖了，之前挂在Amazon云上的，现在找不到这个压缩包了。
